// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// CVfastCpp
double CVfastCpp(const arma::mat& x, const arma::mat& ky);
RcppExport SEXP MAVE_CVfastCpp(SEXP xSEXP, SEXP kySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ky(kySEXP);
    rcpp_result_gen = Rcpp::wrap(CVfastCpp(x, ky));
    return rcpp_result_gen;
END_RCPP
}
// MAVEfastCpp
List MAVEfastCpp(NumericVector x, NumericVector y, CharacterVector method, NumericVector which_dim);
RcppExport SEXP MAVE_MAVEfastCpp(SEXP xSEXP, SEXP ySEXP, SEXP methodSEXP, SEXP which_dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type method(methodSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type which_dim(which_dimSEXP);
    rcpp_result_gen = Rcpp::wrap(MAVEfastCpp(x, y, method, which_dim));
    return rcpp_result_gen;
END_RCPP
}
// PredictCpp
arma::colvec PredictCpp(const arma::mat& x, const arma::mat& newx, const arma::colvec& y);
RcppExport SEXP MAVE_PredictCpp(SEXP xSEXP, SEXP newxSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type newx(newxSEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(PredictCpp(x, newx, y));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"MAVE_CVfastCpp", (DL_FUNC) &MAVE_CVfastCpp, 2},
    {"MAVE_MAVEfastCpp", (DL_FUNC) &MAVE_MAVEfastCpp, 4},
    {"MAVE_PredictCpp", (DL_FUNC) &MAVE_PredictCpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_MAVE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
