// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// CVfastCpp
arma::rowvec CVfastCpp(const arma::mat& x, const arma::mat& ky, const arma::colvec& BB1D);
RcppExport SEXP MAVE_CVfastCpp(SEXP xSEXP, SEXP kySEXP, SEXP BB1DSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type ky(kySEXP);
    Rcpp::traits::input_parameter< const arma::colvec& >::type BB1D(BB1DSEXP);
    rcpp_result_gen = Rcpp::wrap(CVfastCpp(x, ky, BB1D));
    return rcpp_result_gen;
END_RCPP
}
// MAVEfastCpp
List MAVEfastCpp(NumericVector x, NumericVector y, CharacterVector method);
RcppExport SEXP MAVE_MAVEfastCpp(SEXP xSEXP, SEXP ySEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(MAVEfastCpp(x, y, method));
    return rcpp_result_gen;
END_RCPP
}
