# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CVfastCpp <- function(x, ky, BB1D) {
    .Call('MAVE_CVfastCpp', PACKAGE = 'MAVE', x, ky, BB1D)
}

MAVEfastCpp <- function(x, y, method) {
    .Call('MAVE_MAVEfastCpp', PACKAGE = 'MAVE', x, y, method)
}

